name: single_gp
population_size: 1000
generation_num: 100
arity: 6
cxpb: 0.8
mutpb: 0.2
elitism_size: 50
tournament_size: 7
min_depth: 1
max_depth: 6
mut_min_depth: 0
mut_max_depth: 4
testcase_num: 100
cpu_num: 50